# config/services.yaml

parameters:
    pdf_crowd_api_key: '2489143cb8f69238d8debd32a77ee06b'
    pdf_crowd_username: 'malek'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $stripeSK: "%env(STRIPE_SK)%"

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\PdfController:
        arguments:
            $pdfCrowdApiKey: '%pdf_crowd_api_key%'
            $pdfCrowdUsername :  '%pdf_crowd_username%'